=== jmmenah/examples-java/Tema 8/examples/XML-Validation/howto.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="howto">
     <xs:complexType>
      <xs:sequence>
        <xs:element name="topic" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="url" type="httpURI"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:simpleType name="httpURI">
      <xs:restriction base="xs:anyURI">
        <xs:pattern value="http://.*" />
      </xs:restriction>
  </xs:simpleType>
 
</xs:schema>

=== jmmenah/examples-java/Tema 8/examples/XML-Validation/howto2.xml
<?xml version="1.0" encoding="UTF-8"?>
<howto xsi:noNamespaceSchemaLocation="howto.xsd"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <topic>
      <title>Java</title>
      <url>http://www.rgagnon.com/topics/java-xml.html</url>
  </topic>
  <topic>
      <title>PowerBuilder</title>
      <url>http://www.rgagnon.com/topics/pb-powerscript.htm</url>
  </topic>
  <topic>
        <title>Javascript</title>
        <url>http://www.rgagnon.com/topics/js-language.html</url>
  </topic>
  <topic>
        <title>VBScript</title>
        <url>http://www.rgagnon.com/topics/wsh-vbs.html</url>
  </topic>
</howto>
